### PR TITLE
git merge option fix for unrelated histories

### PR DESCRIPTION
**Pull request by andrewhsu**
https://git-scm.com/docs/git-merge#git-merge---allow-unrelated-histories

Signed-off-by: Andrew Hsu <andrewhsu@docker.com>

### CODE REVIEW

**Comment by andrewhsu** [comment]
cc @seemethere

**Review by seemethere — APPROVED** [review]
LGTM

**Comment by seemethere** [comment]
cc @tiborvass

**Comment by tiborvass** [comment]
oopsies LGTM

**Pull request merged**
